
nameOverride: ""
fullnameOverride: ""  

# If a GKE private cluster define the internal API IP. Obtain it by logging in to your GCP project using gcloud and then typing:
# gcloud container clusters describe <gke-cluster-name> --zone=<gke-cluster-zone> | grep privateEndpoint | awk '{print $NF}'
# If not a GKE private cluster, comment out this entry so that the server IP from kubeconfig is used   
kubernetesInternalApiServer: 172.16.0.2

# Image used for the job that will apply the operator yaml files for the relevant command (see below)
image:
  repository: gcr.io/saas-dev-us-cstack-gke1/gdu1/elastic-operator/elasticsearch-operator
  tag: 1.1.5
  pullPolicy: IfNotPresent
 
#kubernetesNamespace: "elasticsearch-operator-demo"
 
podName: "elastic-operator-0"    
  
# Command to run. Applies yaml from the operator folder:

## deploy-cluster:  Following command will be used to deploy elasticsearch cluster, scaleup, scale down, plugin instalation
## delete-cluster:  Following command will delete the elasticsearch cluster 
## provision-kibana: use the following command to provision kibana, Elastic search cluster has to be deployed first for this operation to work
## deprovision-kibana: use the following command to de-provision kibana , Elastic search cluster has to be deployed first for this operation to work
## create-custom-user-role: Use the following command after the cluster has been deployed and follow readme for the prerequisites required to run this command
## enable-backup-cron-job: Use the following command after the cluster has been deployed and follow readme for the prerequisites required to run this command
## deploy-curator: Use the following command after the cluster has been deployed and follow readme for the prerequisites required to run this command
## delete-curator: Use the following command to delete curator cronjob from your namespace
## smoke-test: use this command to trigger a sanity check for the elasticsearch cluster, please change the cluseterName with the name of ES cluster

command: provision-kibana

# change the below value to true if you want to run a sanity check against ES cluster
esSmokeTest: true
  
# Mention the elasticsearch clustername for ensure a sanity check with the help of `smoke-test` command 
clusterName: elasticsearch-config

# change 'deploy-aiops-agent' 'true' if you want to to deploy the operators aiops metrics agent
deployAiopsAgent: true

#change 'deployCuratorJob' 'true' if you want to deploy curator for ILM, Please change the required actions and filters in operators folder(curator-config.yaml)
deployCuratorJob: false

