customRoleSecret: |-  
  kind: Secret
  apiVersion: v1
  metadata:
    name: custom-role-secret
  stringData:
    roles.yml: |-
      #customrolename
      click_admins:
        run_as: [ 'clicks_watcher_1' ]
        cluster: [ 'monitor' ]
        indices:
        - names: [ 'events-*' ]
          privileges: [ 'read' ]
          field_security:
            grant: ['category', '@timestamp', 'message' ]
          query: '{"match": {"category": "click"}}'
      click_admins_role_new:
        run_as: [ 'clicks_watcher_1' ]
        cluster: [ 'monitor' ]
        indices:
        - names: [ 'events-*' ]
          privileges: [ 'write' ]
          field_security:
            grant: ['category', '@timestamp', 'message' ]
          query: '{"match": {"category": "click"}}'
       #Mention Multiple roles
