apiVersion: v1
kind: PersistentVolume
metadata:
  name: cereview-pv
  labels:
    app: ce-review
    project: rnd-repo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /home/Raj/ce-review-data


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cereview-pvc
  labels:
    app: ce-review
    project: rnd-repo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: ce-review
      project: rnd-repo
  storageClassName: manual

