apiVersion: v1
kind: Service
metadata:
  name: ce-review-svc
  labels:
    project: rnd-repo
spec:
  type: NodePort
  ports:
    - targetPort: 7070
      port: 7070
      protocol: TCP
      nodePort: 30011
  selector:
    project: rnd-repo


