rbacYaml: |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: elastic-operator
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: elastic-stack-operator
  subjects:
  - kind: ServiceAccount
    name: elastic-operator
    
