roleBindingLogstashYaml: |-  
  kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: logstash-operator
  subjects:
  - kind: ServiceAccount
    name: logstash-operator
  roleRef:
    kind: Role
    name: logstash-operator
    apiGroup: rbac.authorization.k8s.io
