userManagementFilerealmSecret: |-  
  kind: Secret
  apiVersion: v1
  metadata:
    name: user-management-filerealm-secret
  stringData:
    users: |-
      es-monitor:$2a$10$GEV4f3gMt2VxaxJq0HlxPOnMwQ2mQ2QGZMHV1gWWoAZCTwS9VZ5DC
      es-admin:$2a$10$.r42SdF5f0u1RYTlMozXeun5KXku4etghyNh93GGYKRBNXhZnmgXu
      es-dashboard:$2a$10$jqVuUtdI1n.s/46HaKsDleGRYPcznwQjfUOATHpxHRDcXA4ZPRV7a
      es-click-admin-new:$2a$10$jqVuUtdI1n.s/46HaKsDleGRYPcznwQjfUOATHpxHRDcXA4ZPRV7a
    users_roles: |-
      kibana_dashboard_only_user:es-dashboard
      monitoring_user:es-monitor
      kibana_user:es-monitor
      superuser:es-admin
      click_admins_role_new:es-click-admin-new
